node {
    
    
    stage ('Clone') {
        	echo "Cloining ********************"
        }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}
